### ISSUE TITLE
"ELEVENTY_ENV" not found, App doesn't start

### ISSUE THREAD

**Issue by AlexanderDowerk** [kailoon/kailoon.com#2]
After installing the App and running `npm start`, I just receive the following error: 

![image](https://user-images.githubusercontent.com/10029073/155144689-9f09485a-247c-4bb5-ae72-1f8d52c84657.png)

**Comment by kailoon** [comment]
Hmm... I couldn't replicate the problem tho 
![image](https://user-images.githubusercontent.com/151661/155155841-4803d646-7700-4693-96ae-173c83bc1033.png)

Anyway, I just updated all the packages to the latest version.

**Comment by AlexanderDowerk** [comment]
I guess it's my fault. 
I didn't know I need to define the environment variables first.

**Comment by kailoon** [comment]
No problem.

**Comment by AlexanderDowerk** [comment]
Could you please link the documentation about adding the environment variables in the readme? 
I guess I'm not the only one who expects to be able to run the app without further configuration.
