### ISSUE TITLE
How to change the fonts and colors of the starter?

### ISSUE THREAD

**Issue by shoverian** [kailoon/kailoon.com#3]
Hi  -- I have been playing with it for a little while, but I can't figure out why the `tailwind.config.js` changes aren't showing up. I tried changing the fonts (per [Tailwind docs](https://tailwindcss.com/docs/font-family)).

- `fontFamily: {
			sans: [
				'"Sofia Sans"',
			],
			serif: [
				'Georgia',
				'Times New Roman',
				'serif'
			],
			mono: [
				'"IBM Plex Mono"'
			]
		}`

I also updated `base.njk` to replace line 36 and line 37 reference to Inter and other fonts.

- **Line 36**
`<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&family=Sofia+Sans:wght@400;700;900&display=swap" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">`

- **Line 38**
`<link
        href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&family=Sofia+Sans:wght@400;700;900&display=swap"
        rel="stylesheet"
        type="text/css"
    />`

- **Commented out line 32** 
`<style>@font-face...` since it was referencing other fonts.

All these changes and I see the minified `src/css/styles.css` is still referencing the original Inter font like it's not detecting the changes in `tailwind.config.js` and `base.njk`.

Thanks in advance for any help.

**Comment by kailoon** [comment]
Hi there,

That's because I loaded the wrong generated styles file, sorry about that. The package is updated and I did a little bit of clean up in **base.njk** like removing inline styles. I tested with the code you provided, it should works now.

Let me know :)

**Comment by shoverian** [comment]
It works! Thanks for sharing this starter too. It's structured very well and making 11ty easier to learn.
